#!/usr/bin/env python3
# addons/python-demo-nginx/disable

import click
import os
import subprocess

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")
HELM = os.path.expandvars("$SNAP/microk8s-helm3.wrapper")

@click.command()
def main():
    click.echo("Disabling SB registry")
    subprocess.run([HELM, "delete", "sb-registry"])
    click.echo("Disabled SB registry")

if __name__ == "__main__":
    main()
