#!/usr/bin/env python3

import os
import subprocess

import click

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")
HELM = os.path.expandvars("$SNAP/microk8s-helm3.wrapper")
MICROK8S_STATUS = os.path.expandvars("$SNAP/microk8s-status.wrapper")
MICROK8S_ENABLE = os.path.expandvars("$SNAP/microk8s-enable.wrapper")

@click.command()
def main():
    args = []
    args.extend(["--set", "imageAutomationController.create=false"])
    args.extend(["--set", "imageReflectionController.create=false"])
    args.extend(["--set", "kustomizeController.create=false"])
    args.extend(["--set", "notificationController.create=false"])
    args.extend(["--set", "sourceController.create=false"])

    subprocess.run([HELM, "repo", "add", "flux",
                   "https://fluxcd-community.github.io/helm-charts"])
    subprocess.run([HELM, "repo", "update"])
    subprocess.run([HELM, "install", "helm-operator", "flux/flux2", "--create-namespace", "--namespace", "flux", *args])
    click.echo("Enabled Flux helm controller")

if __name__ == "__main__":
    main()
