#!/usr/bin/env python3

import click
import os
import subprocess
from pathlib import Path

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")

@click.command()
def main():
    click.echo("Disabling cluster issuer")
    subprocess.check_call([
        KUBECTL, "delete", "clusterissuer", "letsencrypt-prod"
    ])
    Path('/var/lock/sb-cluster-issuer.enabled').unlink()
    click.echo("Disabled cluster issuer")

if __name__ == "__main__":
    main()
