#!/usr/bin/env python3

import click
import os
import subprocess

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")
HELM = os.path.expandvars("$SNAP/microk8s-helm3.wrapper")

@click.command()
def main():
    click.echo("Disabling Kpack")
    subprocess.run([HELM, "delete", "kpack", "--namespace", "kpack"])
    click.echo("Disabled Kpack")

if __name__ == "__main__":
    main()
