#!/usr/bin/env python3

import click
import os
import subprocess

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")

@click.command()
def main():
    click.echo("Deleting sb-operator")
    subprocess.check_call([
        KUBECTL, "delete", "deploy", "sb-operator"
    ])
    click.echo("Deleting sb-operator")

if __name__ == "__main__":
    main()
